create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.admin_bootstrap_invites (
  email text primary key,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

create or replace function public.claim_admin_access()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  claim_email text := lower(coalesce((auth.jwt() ->> 'email'), ''));
  claim_user_id uuid := auth.uid();
begin
  if claim_user_id is null or claim_email = '' then
    raise exception 'No authenticated user was found.';
  end if;

  if not exists (
    select 1
    from public.admin_bootstrap_invites
    where lower(email) = claim_email
  ) then
    raise exception 'This email is not approved for initial admin setup.';
  end if;

  insert into public.admin_users (user_id, email)
  values (claim_user_id, claim_email)
  on conflict (user_id) do update
  set email = excluded.email;

  delete from public.admin_bootstrap_invites
  where lower(email) = claim_email;

  return true;
end;
$$;

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint topics_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.stances (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  summary text not null default '',
  body text not null default '',
  status text not null default 'draft',
  topic_id bigint references public.topics(id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint stances_status_check check (status in ('draft', 'published', 'archived')),
  constraint stances_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.in_progress_items (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  summary text not null default '',
  body text not null default '',
  status text not null default 'active',
  priority integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint in_progress_status_check check (status in ('backlog', 'active', 'blocked', 'done')),
  constraint in_progress_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  summary text not null default '',
  body text not null default '',
  status text not null default 'draft',
  topic_id bigint references public.topics(id) on delete set null,
  featured boolean not null default false,
  homepage boolean not null default false,
  stance_id bigint references public.stances(id) on delete set null,
  linked_model_id bigint,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint posts_status_check check (status in ('draft', 'published', 'archived')),
  constraint posts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.models (
  id bigint generated by default as identity primary key,
  title text not null,
  version text not null,
  file_path text not null unique,
  post_id bigint references public.posts(id) on delete set null,
  topic_id bigint references public.topics(id) on delete set null,
  uploaded_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.site_settings (
  key text primary key,
  label text not null,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_linked_model_id_fkey'
      and conrelid = 'public.posts'::regclass
  ) then
    alter table public.posts
      add constraint posts_linked_model_id_fkey
      foreign key (linked_model_id) references public.models(id) on delete set null;
  end if;
end $$;

create index if not exists topics_sort_order_idx on public.topics (sort_order, name);
create index if not exists stances_topic_id_idx on public.stances (topic_id);
create index if not exists stances_status_idx on public.stances (status, published_at desc);
create index if not exists in_progress_status_idx on public.in_progress_items (status, priority desc);
create index if not exists posts_topic_id_idx on public.posts (topic_id);
create index if not exists posts_stance_id_idx on public.posts (stance_id);
create index if not exists posts_linked_model_id_idx on public.posts (linked_model_id);
create index if not exists posts_status_published_idx on public.posts (published_at desc, id desc)
where status = 'published';
create index if not exists posts_status_updated_idx on public.posts (status, updated_at desc);
create index if not exists posts_homepage_idx on public.posts (homepage, featured, published_at desc);
create index if not exists models_post_id_idx on public.models (post_id);
create index if not exists models_topic_id_idx on public.models (topic_id);
create index if not exists models_uploaded_at_idx on public.models (uploaded_at desc);

drop trigger if exists set_topics_updated_at on public.topics;
create trigger set_topics_updated_at
before update on public.topics
for each row
execute function public.set_updated_at();

drop trigger if exists set_stances_updated_at on public.stances;
create trigger set_stances_updated_at
before update on public.stances
for each row
execute function public.set_updated_at();

drop trigger if exists set_in_progress_updated_at on public.in_progress_items;
create trigger set_in_progress_updated_at
before update on public.in_progress_items
for each row
execute function public.set_updated_at();

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

drop trigger if exists set_models_updated_at on public.models;
create trigger set_models_updated_at
before update on public.models
for each row
execute function public.set_updated_at();

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
before update on public.site_settings
for each row
execute function public.set_updated_at();

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.claim_admin_access() to authenticated;

grant select on public.topics to anon;
grant select on public.posts to anon;
grant select on public.stances to anon;
grant select on public.models to anon;
grant select on public.site_settings to anon;

grant select, insert, update, delete on public.admin_users to authenticated;
grant select, insert, update, delete on public.admin_bootstrap_invites to authenticated;
grant select, insert, update, delete on public.topics to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, update, delete on public.stances to authenticated;
grant select, insert, update, delete on public.in_progress_items to authenticated;
grant select, insert, update, delete on public.models to authenticated;
grant select, insert, update, delete on public.site_settings to authenticated;

alter table public.admin_users enable row level security;
alter table public.admin_bootstrap_invites enable row level security;
alter table public.topics enable row level security;
alter table public.stances enable row level security;
alter table public.in_progress_items enable row level security;
alter table public.posts enable row level security;
alter table public.models enable row level security;
alter table public.site_settings enable row level security;

alter table public.admin_users force row level security;
alter table public.admin_bootstrap_invites force row level security;
alter table public.topics force row level security;
alter table public.stances force row level security;
alter table public.in_progress_items force row level security;
alter table public.posts force row level security;
alter table public.models force row level security;
alter table public.site_settings force row level security;

drop policy if exists "Admin users can read their own record" on public.admin_users;
create policy "Admin users can read their own record"
on public.admin_users
for select
to authenticated
using ((select auth.uid()) = user_id or (select public.is_admin()));

drop policy if exists "Admins can manage admin users" on public.admin_users;
create policy "Admins can manage admin users"
on public.admin_users
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can manage bootstrap invites" on public.admin_bootstrap_invites;
create policy "Admins can manage bootstrap invites"
on public.admin_bootstrap_invites
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Public can view visible topics" on public.topics;
create policy "Public can view visible topics"
on public.topics
for select
to anon, authenticated
using (is_visible);

drop policy if exists "Admins can manage topics" on public.topics;
create policy "Admins can manage topics"
on public.topics
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Public can view published stances" on public.stances;
create policy "Public can view published stances"
on public.stances
for select
to anon, authenticated
using (status = 'published');

drop policy if exists "Admins can manage stances" on public.stances;
create policy "Admins can manage stances"
on public.stances
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can manage in-progress items" on public.in_progress_items;
create policy "Admins can manage in-progress items"
on public.in_progress_items
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Public can view published posts" on public.posts;
create policy "Public can view published posts"
on public.posts
for select
to anon, authenticated
using (status = 'published');

drop policy if exists "Admins can manage posts" on public.posts;
create policy "Admins can manage posts"
on public.posts
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Public can view published models" on public.models;
create policy "Public can view published models"
on public.models
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.posts
    where posts.id = models.post_id
      and posts.status = 'published'
  )
);

drop policy if exists "Admins can manage models" on public.models;
create policy "Admins can manage models"
on public.models
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Public can view public site settings" on public.site_settings;
create policy "Public can view public site settings"
on public.site_settings
for select
to anon, authenticated
using (is_public);

drop policy if exists "Admins can manage site settings" on public.site_settings;
create policy "Admins can manage site settings"
on public.site_settings
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'models',
  'models',
  false,
  104857600,
  array[
    'application/pdf',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/zip',
    'text/csv'
  ]
)
on conflict (id) do nothing;

drop policy if exists "Public can view published model files" on storage.objects;
create policy "Public can view published model files"
on storage.objects
for select
to anon, authenticated
using (
  bucket_id = 'models'
  and exists (
    select 1
    from public.models
    join public.posts on posts.id = models.post_id
    where models.file_path = name
      and posts.status = 'published'
  )
);

drop policy if exists "Admins can manage model files" on storage.objects;
create policy "Admins can manage model files"
on storage.objects
for all
to authenticated
using (bucket_id = 'models' and (select public.is_admin()))
with check (bucket_id = 'models' and (select public.is_admin()));

insert into public.site_settings (key, label, value, is_public)
values
  (
    'homepage',
    'Homepage',
    jsonb_build_object(
      'showFeatured', true,
      'showDeskBriefs', true,
      'showLatestResearch', true,
      'showMarketNotes', true,
      'showStances', true,
      'heroLabel', 'Today''s Desk',
      'featuredPostSlug', '',
      'latestResearchLimit', 4,
      'marketNotesLimit', 6,
      'orderedPostSlugs', '[]'::jsonb,
      'orderedStanceSlugs', '[]'::jsonb
    ),
    true
  ),
  (
    'general',
    'General Settings',
    jsonb_build_object(
      'siteTitle', 'Whiteprint Research',
      'siteDescription', 'Independent macro and equity research',
      'brandTagline', 'Clarity over consensus.',
      'contactEmail', '',
      'navCtaLabel', 'Get in touch'
    ),
    true
  )
on conflict (key) do nothing;

insert into public.admin_bootstrap_invites (email)
values ('chirayuparikh7@gmail.com')
on conflict (email) do nothing;
